### ISSUE TITLE
API Milestone 5 (November 2022)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#1]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-november-2022--milestone)

- [x] [Change 1](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-1-6): `committeeReport` -> `committee-report` and related item changes
- [x] [Change 2](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-2-4) `committee` gains `senate-communication` endpoint
- [x] [Change 3](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-3-3) `nomination` list and item name changes
- [x] [Change 4](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-4-1) `member` bug fix, no downstream change
