### ISSUE TITLE
API Milestone 13 (June 2023)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#10]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#upcoming-june-2023-part-2--milestone)

- [x] [Change 1](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-1): `member` endpoint structure changed
- [x] [Change 2](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-2): `amendment` endpoint URL changes
- [x] [Change 3](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-3): `amendment` endpoint includes congress of origin for treaties
- [x] [Change 4](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-4): `committee-print` without a committee
- [x] [Change 5](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-5): `member` endpoint gains an updateDate
- [x] [Change 6](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-6): base url to `api.congress.gov/v3`
