### ISSUE TITLE
API Milestone 14 (July 2023)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#11]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-july-2023--milestone)

- [x] [Change 1](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-1-10): New daily Congressional Record endpoint
- [x] [Change 3](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-3-8): `house-requirement`  `submittingOfficial` was suppressed upstream
- [x] [Change 4](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-4-5): `committee-print` some items were suppressed upstream
- [x] [Change 5](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-5-5): `bill` some items were suppressed upstream
- [x] [Change 6](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-6-1): `house-communication` check pagination changes
