### ISSUE TITLE
API Milestone 15 (August 2023)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#12]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-august-2023-part-1--milestone), [Part 2](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-august-2023-part-2)

- [x] Change 1: `house-communication` returns more info, check processing
- [x] Change 2: reserved bills added to `bill` endpoints, check processing
- [x] Change 3: allow for issue level re changes to `daily-congressional-record/{volumeNumber}/{issueNumber}`
- [x] Part 2, Change 1: New API endpoint for `bound-congressional-record`
