### ISSUE TITLE
API Milestone 16 (September 2023)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#13]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-september-2023--milestone)

- [x] Change 1: `hearing` endpoint now includes referrer URL as `associatedMeeting`, check processing
- [x] Change 2: location error in `committee-meeting` enpoints, check processing
- [x] Change 3: verify all calls are lowercase, e.g. `hr` not `HR`
