### ISSUE TITLE
API Milestone 17 (October 2023)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#14]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-october-2023-part-1-milestone)

- [x] Change 1: `committee` endpoint offset issue, check processing
- [x] Change 2: `nomination` endpoint date updates, check processing
- [x] Change 3: `bill` reserved bill updates, check processing
- [x] Change 4:  `bill/{congress}` updates to DateTime processing, check processing
- [x] Change 5: `house-communication` bug fix, check processing
