### ISSUE TITLE
API Milestone 18 (October 2023)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#15]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-october-2023-part-2-milestone)

- [x] Change 1: `amendment` adds `text` and `type`, check processing
- [x] Change 2: `nomination` date times types changed, may need type conversion updates
- [x] Change 3:  `committee` updates, check processing
