### ISSUE TITLE
API Milestone 20 (December 2023)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#16]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-december-2023-milestone)

- [x] Change 1: `amendment` updateDate changed upstream, check processing
- [x] Change 2: `committee-meeting` URLs are updated, check processing
- [x] Change 3: resigned members are no longer listed as current in `member`, check processing
- [x] Change 4: for congress >= 117, `amendment` has a new text endpoint
- [x] Change 5: `bound-congressional-record` pdfs are incorporated into endpoint, check processing
