### ISSUE TITLE
API Milestone 6 (November 2022)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#2]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-november-2022-part-2)

- [ ] []() `committee` new endpoints
- [ ] []() `nomination` endpoints renamed
- [ ] []() `committee` now takes `fromDate` and `toDate` arguments for `committee reports`

**Comment by christopherkenny** [comment]
Change 3 was already allowed in 0.0.1

**Comment by christopherkenny** [comment]
Change 2 is handled automatically by `clean_names()` (internally).

**Comment by christopherkenny** [comment]
Change 1 is also handled automatically by clean_names() (internally).
