### ISSUE TITLE
API Milestone 10 (February 2023)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#6]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-february-2023--milestone)

- [x] [Change 1](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-1-1) new `house-communication` endpoint in `committee/house/{committeeCode}/house-communication`
- [x] [Change 2](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#impacted-endpoint-senate-communicationcongresscommunicationtypecommunicationnumber) `senate-communication` gains `?format=` for `json` or `xml`.
- [x] [Change 3](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-3-1) `member` no longer returns empty elements (may require `any_of()` specification)
- [x] [Change 4](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-4) `committee` no longer returns empty elements (may require `any_of()` specification)
- [x] [Change 5](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#impacted-endpoint-amendment) `amendment` bug fix, no downstream change

**Comment by christopherkenny** [comment]
Does not need `any_of()` for Changes 3 or 4.
