### ISSUE TITLE
API Milestone 12 (May 2023)

### ISSUE THREAD

**Issue by christopherkenny** [christopherkenny/congress#9]
[Details from ChangeLog](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#completed-june-2023--milestone)

- [x] [Change 1](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-1-1): `commitee-meeting` empty elements suppressed
- [x] [Change 2](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-2-1): `bill` endpoints can have new numbers
- [x] [Change 3](https://github.com/LibraryOfCongress/api.congress.gov/blob/main/ChangeLog.md#change-3-1): `house-communication` endpoints renamed
